# Data
path: /kaggle/input/finger-gesture-data/Hand Keypoint Dataset
train: images/train  # train images (relative to 'path')
val: images/train  # train images (relative to 'path')

# Keypoints
kpt_shape: [5, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 3 ,4]

# Classes
names:
  0: gesture